### PR TITLE
chore: Use [].map instead of [...nodes].map

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
Uses `Array.prototype.map` directly by providing the NodeList as the `this` argument.
This is achieved by using the `.call` method that JS provides.

```js
Array.prototype.map.call([1, 2, 3], console.log);
```
is the equivalent of
```js
[1, 2, 3].map(console.log)
```

This is just a minor optimization, but squeezing out as much as we can is not a bad thing.

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
This is a pretty cool hack and I really can't see why `.forEach` exists for NodeList but not `.map`.

**Comment by antfu** [comment]
I prefer how it used to be. Performance isn't a concern here. And you shouldn't commit your lock file in PRs.

**Comment by ArjixWasTaken** [comment]
> And you shouldn't commit your lock file in PRs.

~~...you are the one that added the pre-commit hook, it is your doing, not mine~~

~~https://github.com/antfu/refined-github-notifications/blob/main/package.json#L37~~

**Comment by antfu** [comment]
No, this project uses pnpm not npm.

**Comment by ArjixWasTaken** [comment]
what are you even saying?
how does that relate to you having a pre-commit hook?

**Comment by ArjixWasTaken** [comment]
~~and even if it was related in any way, the pre-commit hook uses pnpm
image~~

~~so what you are saying makes no sense even in that scenario~~

**Comment by ArjixWasTaken** [comment]
~~all I did was edit the userscript and make a commit
the commit failed because you have a hook that uses pnpm, i then installed pnpm and retried to make the commit~~

~~the hook ran and added the lockfile to the diff~~

**Comment by ArjixWasTaken** [comment]
~~how is that smth I did?
you are the one that added the pre-commit hook in the package.json~~

**Comment by ArjixWasTaken** [comment]
~~do you just not know what a pre-commit hook is?
did you use a template?~~

**Comment by ArjixWasTaken** [comment]
I swear to god if vscode decided to create a lockfile for no reason I'll kill someone.

**Comment by nate-moo** [comment]
looks like you're gonna kill someone :gun:

**Pull request closed without merging**
